Rust perm verifier 1 3
hyperledger/sawtooth-core pull request #2329
Opened 2020-07-16 20:08 UTC by peterschwarz

2021-03-17 19:23 UTC, vaporos commented
This probably needs a rebase to pass the build.

2021-05-26 19:48 UTC, agunde406 requested changes

2021-05-26 19:48 UTC, agunde406 commented on validator/src/permissions/state_source.rs
> +                            "policy {} is ccontains invalid type",
"policy {} is ccontains invalid type" => "policy {} contains invalid type"

2021-05-26 19:54 UTC, agunde406 approved these changes

2021-06-10 20:49 UTC, vaporos approved these changes

2021-06-10 20:49 UTC, merged