Fix panic w/non-static String compiler warning
hyperledger/sawtooth-core pull request #2380
Opened 2021-06-04 21:12 UTC by vaporos

The solution here is to reduce it a simple string, which isn't ideal
since it will no longer print the missing transaciton type. However,
this code is unrefined anyway since it panics at all, and the solution
of rewriting it with proper error handling can happen in a future change
aimed at removing the panics.

2021-06-07 12:57 UTC, agunde406 requested changes

2021-06-07 12:57 UTC, agunde406 commented on perf/smallbank_workload/src/playlist.rs
> +                Some(_) => panic!("unknown tryansaction type specified"),
tryansaction => transaction

2021-06-09 18:42 UTC, peterschwarz submitted a review, later dismissed

2021-06-09 18:43 UTC, vaporos commented on perf/smallbank_workload/src/playlist.rs
> +                Some(_) => panic!("unknown tryansaction type specified"),
fixed. also made the solution simpler.

2021-06-09 18:45 UTC, agunde406 approved these changes

2021-06-10 13:02 UTC, agunde406 approved these changes

2021-06-10 13:55 UTC, merged