Add batch show subcommand to sawadm CLI
hyperledger/sawtooth-core pull request #2402
Opened 2021-10-29 21:08 UTC by CLEckhardt

Signed-off-by: Chris Eckhardt <eckhardt@bitwise.io>

2021-10-29 21:13 UTC, agunde406 requested changes

2021-10-29 21:13 UTC, agunde406 commented on adm/src/main.rs
> +                        "Displays informatino for the specified Batch."
Typo: informatino -> information

2021-10-29 21:13 UTC, agunde406 commented on adm/src/main.rs
> +                            "identify the URL of the validator's\n\
avoid new lines in the clap help

2021-11-04 14:10 UTC, isabeltomb commented on adm/src/commands/batch.rs
> +            .collect::<Result<Vec<DisplayBatchListItem>, SawtoothClientError>>()
Looks like since the duplicate `SawtoothClientError` import is being removed, this should be changed to `ClientError`

2021-11-04 14:35 UTC, isabeltomb approved these changes

2021-11-04 16:08 UTC, agunde406 approved these changes

2021-11-04 17:00 UTC, peterschwarz approved these changes

2021-11-04 17:00 UTC, merged